/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.JOptionPane;
import Model.Users1;
import Service.UsersInterfaceService;
import Serviceimpl.UsersService1;

/**
 *
 * @author H
 */
public class dang_Nhap1 extends javax.swing.JFrame {
    boolean hish = false;
    UsersService1 service = new UsersService1();

    /**
     * Creates new form dang_Nhap1
     */
    public dang_Nhap1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new swing.MyTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new swing.MyPassword();
        btnExit = new swing.MyButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_thongBao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new swing.MyButton();
        hideshow = new javax.swing.JLabel();
        quenmatkhau1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setMinimumSize(new java.awt.Dimension(300, 40));
        txtUser.setName(""); // NOI18N
        txtUser.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 620, 41));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đăng nhập");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 140, 40));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPass.setMinimumSize(new java.awt.Dimension(300, 40));
        txtPass.setPreferredSize(new java.awt.Dimension(300, 40));
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 620, 40));

        btnExit.setBackground(new java.awt.Color(125, 224, 237));
        btnExit.setForeground(new java.awt.Color(0, 0, 51));
        btnExit.setText("Thoát");
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 220, 48));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mật khẩu");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 390, 24));

        lbl_thongBao.setForeground(new java.awt.Color(255, 51, 51));
        lbl_thongBao.setBorder(null);
        lbl_thongBao.setContentAreaFilled(false);
        lbl_thongBao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lbl_thongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 340, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tài khoản");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 400, 24));

        btnLogin.setBackground(new java.awt.Color(125, 224, 237));
        btnLogin.setForeground(new java.awt.Color(0, 0, 51));
        btnLogin.setText("Đăng nhập");
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 220, 48));

        hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        hideshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideshowMouseClicked(evt);
            }
        });
        jPanel2.add(hideshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 470, 40, 40));

        quenmatkhau1.setForeground(new java.awt.Color(255, 51, 51));
        quenmatkhau1.setText("Quên mật khẩu ?");
        quenmatkhau1.setBorder(null);
        quenmatkhau1.setContentAreaFilled(false);
        quenmatkhau1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(quenmatkhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 100, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Store (3).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1194, -1));

        panelGradiente1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPassKeyPressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int chon = JOptionPane.showConfirmDialog(this, "bạn chắc chắn muốn thoát");
        if (chon == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String taiKhoan = txtUser.getText();
    String matkhau = txtPass.getText();

    if (taiKhoan.isEmpty()) { 
        JOptionPane.showMessageDialog(this, "Mời Bạn Nhập tài khoản");
    } else if (matkhau.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mời Bạn Nhập mật khẩu");
    } else {
        // Kiểm tra xem service đã được khởi tạo hay chưa
        if (service != null) {
            List<Users1> list = service.getUser(taiKhoan, matkhau);

            if (list != null && !list.isEmpty()) {
                for (Users1 u : list) {
                    if ("quản lý".equals(u.getChucVu().getTen())) {
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công! (Quản Lý)");
                        this.dispose();
                         home homeFrame = new home(taiKhoan, WIDTH, matkhau);
                         homeFrame.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công! (nhân viên)");
                        this.dispose();
                         home homeFrame = new home(taiKhoan, WIDTH, matkhau);
                         homeFrame.setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sai Tài Khoản Hoặc Mật Khẩu");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Service chưa được khởi tạo.");
            // Thực hiện xử lý khi service không được khởi tạo
        }
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void hideshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideshowMouseClicked
        if (hish == false) {
            hish = true;
            hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtPass.setEchoChar((char) 0);
        } else {
            hish = false;
            hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtPass.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_hideshowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dang_Nhap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dang_Nhap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dang_Nhap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dang_Nhap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dang_Nhap1().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton btnExit;
    private swing.MyButton btnLogin;
    private javax.swing.JLabel hideshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lbl_thongBao;
    private swing.PanelGradiente panelGradiente1;
    private javax.swing.JButton quenmatkhau1;
    private swing.MyPassword txtPass;
    private swing.MyTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
