/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.HoaDon1;
import Model.HoaDonChiTiet;
import Model.MauSac;
import Serviceimpl.HoaDonService;

/**
 *
 * @author H
 */
public class HoaDonv extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    HoaDonService service = new HoaDonService();
    int page=1;
    int limit=5;

    /**
     * Creates new form HoaDon
     */
    public HoaDonv() {
        initComponents();
        
        loadTableHoaDon(page, limit);
        jLabel2.setText(Integer.toString(page));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGradiente1 = new swing.PanelGradiente();
        panelBorder1 = new swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        panelBorder3 = new swing.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        txt_tk = new swing.SearchText();
        cbo_trangthai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelBorder2 = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HoaDonCT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 640));

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(255, 204, 255));

        panelBorder1.setBackground(new java.awt.Color(204, 204, 255));

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MA", "TÊN NHÂN VIÊN", "TÊN KHÁCH HÀNG", "TỔNG TIỀN", "NGÀY TẠO", "NGÀY TT", "TRẠNG THÁI", "GHI CHÚ"
            }
        ));
        tbl_hoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_hoadon.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hoadon);

        panelBorder1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 990, 140);

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelBorder3.add(jLabel3);
        jLabel3.setBounds(750, 0, 40, 40);

        txt_tk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tkMouseClicked(evt);
            }
        });
        txt_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tkActionPerformed(evt);
            }
        });
        txt_tk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tkKeyReleased(evt);
            }
        });
        panelBorder3.add(txt_tk);
        txt_tk.setBounds(10, 0, 730, 40);

        panelBorder1.add(panelBorder3);
        panelBorder3.setBounds(100, 30, 810, 40);

        cbo_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đã thanh toán" }));
        cbo_trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangthaiActionPerformed(evt);
            }
        });
        panelBorder1.add(cbo_trangthai);
        cbo_trangthai.setBounds(180, 120, 220, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Trạng thái");
        panelBorder1.add(jLabel5);
        jLabel5.setBounds(180, 100, 220, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Hóa Đơn");
        panelBorder1.add(jLabel7);
        jLabel7.setBounds(0, 160, 220, 30);

        btnPre.setText("pre");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        panelBorder1.add(btnPre);
        btnPre.setBounds(400, 340, 60, 23);

        btnNext.setText("next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelBorder1.add(btnNext);
        btnNext.setBounds(520, 340, 60, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelBorder1.add(jLabel2);
        jLabel2.setBounds(487, 340, 20, 20);

        panelGradiente1.add(panelBorder1);
        panelBorder1.setBounds(20, 10, 990, 370);

        panelBorder2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Hóa đơn chi tiết");
        panelBorder2.add(jLabel1);
        jLabel1.setBounds(10, 0, 220, 30);

        tbl_HoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HÓA ĐƠN", "ID SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HoaDonCT.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbl_HoaDonCT);

        panelBorder2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 30, 990, 220);

        panelGradiente1.add(panelBorder2);
        panelBorder2.setBounds(20, 390, 990, 250);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangthaiActionPerformed
            String timTT = cbo_trangthai.getSelectedItem().toString();
            model = (DefaultTableModel) tbl_hoadon.getModel();
            ArrayList<Model.HoaDon1> list = service.getAllHoaDon(page, limit);
            model.setRowCount(0);
            for (HoaDon1 HoaDon : list) {
                String trangThaiText ="";
                if (HoaDon.getTrangThai()==0) {
                    trangThaiText="Chưa Thanh Toán";
                }else{
                    trangThaiText="Đã Thanh Toán";
                }
                if (trangThaiText.equalsIgnoreCase(timTT)) {
                    model.addRow(new Object[]{
            HoaDon.getMa(),
            HoaDon.getTenNV(),
            HoaDon.getTenKH(),
            HoaDon.getTongTien(),
            HoaDon.getNgayTao(),
            HoaDon.getNgayTT(),
            HoaDon.getTrangThai() ==0?"Chưa Thanh Toán":"Đã Thanh Toán",
            HoaDon.getGhiChu()});
                }
        }
    }//GEN-LAST:event_cbo_trangthaiActionPerformed

    private void txt_tkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tkKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String timTT = txt_tk.getText().trim().toLowerCase();
        ArrayList<Model.HoaDon1> list = service.getAllHoaDon(page, limit);
        model.setRowCount(0);
        for (HoaDon1 hoaDon : list) {
            String tenKH = hoaDon.getTenKH();
            
            if (tenKH != null && tenKH.toLowerCase().contains(timTT)) {
                model.addRow(new Object[]{
                    hoaDon.getMa(),
                    hoaDon.getTenNV(),
                    hoaDon.getTenKH(),
                    hoaDon.getTongTien(),
                    hoaDon.getNgayTao(),
                    hoaDon.getNgayTT(),
                    (hoaDon.getTrangThai() == 0) ? "Chưa Thanh Toán" : "Đã Thanh Toán",
                    hoaDon.getGhiChu()
                });
            }
        }
    }
    }//GEN-LAST:event_txt_tkKeyReleased

    private void txt_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tkActionPerformed

    private void txt_tkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tkMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tbl_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoadonMouseClicked
        int row = tbl_hoadon.getSelectedRow();
        model = (DefaultTableModel) tbl_HoaDonCT.getModel();
        model.setRowCount(0);
        ArrayList<HoaDonChiTiet> list = service.getAllHoaDonChiTiet(tbl_hoadon.getValueAt(row, 0).toString());
        for (HoaDonChiTiet hdct : list) {
            model.addRow(new Object[]{
                hdct.getMaHoaDon(),
                hdct.getMaSP(),
                hdct.getSoLuong(),
                hdct.getDonGia(),
                hdct.getThanhTien()
            });
        }
    }//GEN-LAST:event_tbl_hoadonMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        page++;
        jLabel2.setText(Integer.toString(page));        
        loadTableHoaDon(page, limit);
        btnPre.setEnabled(true);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        if (page == 1) {
        btnPre.setEnabled(false);
    }else {
            page--;
        jLabel2.setText(Integer.toString(page));
        loadTableHoaDon(page, limit);
        }
    }//GEN-LAST:event_btnPreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonv().setVisible(true);
            }
        });
    }
    
    private void loadTableHoaDon(int page, int limit){
        model = (DefaultTableModel) tbl_hoadon.getModel();
        model.setRowCount(0);
        ArrayList<Model.HoaDon1> list = service.getAllHoaDon(page, limit);
        for (Model.HoaDon1 hd : list) {
            model.addRow(new Object[]{
            hd.getMa(),
            hd.getTenNV(),
            hd.getTenKH(),
            hd.getTongTien(),
            hd.getNgayTao(),
            hd.getNgayTT(),
            hd.getTrangThai() ==0?"Chưa Thanh Toán":"Đã Thanh Toán",
            hd.getGhiChu()});
        }
    }
    
//    private void loadtableHoaDonChiTiet(){
//        model.setRowCount(0);
//        ArrayList<HoaDonChiTiet> list = service.getAllHoaDonChiTiet();
//        for (HoaDonChiTiet hdct : list) {
//            model.addRow(new Object[]{
//                hdct.getMaHoaDon(),
//                hdct.getMaSP(),
//                hdct.getTenSP(),
//                hdct.getSoLuong(),
//                hdct.getDonGia(),
//                hdct.getThanhTien()
//            });
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JComboBox<String> cbo_trangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.PanelBorder panelBorder1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private swing.PanelGradiente panelGradiente1;
    private javax.swing.JTable tbl_HoaDonCT;
    private javax.swing.JTable tbl_hoadon;
    private swing.SearchText txt_tk;
    // End of variables declaration//GEN-END:variables
}
