/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.properties;

import Model.Size;
import Model.ThuongHieu;
import Service.AddNhanh;
import Serviceimpl.AddNhanhImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class addThuongHieu extends javax.swing.JFrame {

    /**
     * Creates new form addThuongHieu
     */
    public addThuongHieu() {
        initComponents();
        loadThuongHieu();
        setLocationRelativeTo(null);
    }
 AddNhanh addNhanhService = new AddNhanhImpl();
    private void loadThuongHieu() {
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);
        List<ThuongHieu> list = addNhanhService.getListThuongHieu();
        for (ThuongHieu size : list) {
            Object rowData[] = {size.getIdThuongHieu(), size.getTenThuongHieu()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente5 = new swing.PanelGradiente();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMuc = new javax.swing.JTable();
        txtThem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradiente5.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente5.setColorSecundario(new java.awt.Color(255, 204, 255));
        panelGradiente5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGradiente5.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 142, -1));

        btnSearch.setText("Tìm kiếm");
        panelGradiente5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "Tên Thương Hiệu"
            }
        ));
        jScrollPane1.setViewportView(tblDanhMuc);

        panelGradiente5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 610, 190));
        panelGradiente5.add(txtThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 152, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        panelGradiente5.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelGradiente5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        getContentPane().add(panelGradiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 636, 275));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String txtDanhMuc = txtThem.getText();
        ThuongHieu dm = new ThuongHieu();
        dm.setTenThuongHieu(txtDanhMuc);
        try {
            addNhanhService.addThuongHieu(dm);
            JOptionPane.showMessageDialog(this, "add thanh cong");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "add that bai");
            e.printStackTrace();
        }
        loadThuongHieu();
    }//GEN-LAST:event_btnThemActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addThuongHieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelGradiente panelGradiente5;
    private javax.swing.JTable tblDanhMuc;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtThem;
    // End of variables declaration//GEN-END:variables
}
