/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.properties;

import Model.KhachHang;
import Serviceimpl.KhachHangService_IMPL;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import views.Khach_Hangg;

/**
 *
 * @author trant
 */
public class KhachHang_BanHang extends javax.swing.JFrame {
    private String idkh;

    public String getIdkh() {
        return idkh;
    }

    public void setIdkh(String idkh) {
        this.idkh = idkh;
    }
    
    /**
     * Creates new form KhachHang_BanHang
     */
    public KhachHang_BanHang() {
        initComponents();
        List<KhachHang> listKH = new KhachHangService_IMPL().getall();
        showTable(listKH);
        setLocationRelativeTo(null);
    }

         public void showTable(List<KhachHang> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_KhachHang_BanHang.getModel();
        defaultTableModel.setRowCount(0);

        for (KhachHang kh : list) {
            Object datarow[] = {
                kh.getId(),
                kh.getHo() + " " + kh.getTendem() + " " + kh.getTen(),
                kh.getGioitinh() == 0 ? "Nam" : "Nữ",
                kh.getNgaysinh(),
                kh.getSdt(),
                kh.getEmail(), 
                kh.getDiemthuong()
            };
            defaultTableModel.addRow(datarow);

        }
    }
         
         public String getIdKH () {
             String idKH = tbl_KhachHang_BanHang.getValueAt(tbl_KhachHang_BanHang.getSelectedRow(), 0)+"";
             return idKH;
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        btnThemKH = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        SdtSearchText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_KhachHang_BanHang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(255, 204, 255));
        panelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemKH.setText("Thêm Khách hàng");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });
        panelGradiente1.add(btnThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 301, 143, -1));

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelGradiente1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 40, 110, -1));
        panelGradiente1.add(SdtSearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 40, 154, -1));

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelGradiente1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 301, 91, -1));

        jButton1.setText("Chọn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelGradiente1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 301, 87, -1));

        tbl_KhachHang_BanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "SĐT", "Email", "Điểm Thưởng"
            }
        ));
        tbl_KhachHang_BanHang.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_KhachHang_BanHang.setRowHeight(25);
        tbl_KhachHang_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHang_BanHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_KhachHang_BanHang);

        panelGradiente1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 720, 194));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelGradiente1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 0, -1, -1));

        getContentPane().add(panelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        Khach_Hangg khView = new Khach_Hangg();
        khView.setVisible(true);
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        List<KhachHang> listKH = new KhachHangService_IMPL().getall();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_KhachHang_BanHang.getModel();
        defaultTableModel.setRowCount(0);

        for (KhachHang kh : listKH) {
            if (kh.getSdt().contains(SdtSearchText.getText())) {
                Object datarow[] = {
                    kh.getId(),
                    kh.getHo() + " " + kh.getTendem() + " " + kh.getTen(),
                    kh.getGioitinh() == 0 ? "Nam" : "Nữ",
                    kh.getNgaysinh(),
                    kh.getSdt(),
                    kh.getEmail(),
                    kh.getDiemthuong()
                };
                defaultTableModel.addRow(datarow);
            }

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = tbl_KhachHang_BanHang.getSelectedRow();
        if (index==-1) {
            JOptionPane.showMessageDialog(this ,"Bạn chưa chọn khách hàng");
        }else {
            this.setIdkh(getIdKH());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_KhachHang_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHang_BanHangMouseClicked

    }//GEN-LAST:event_tbl_KhachHang_BanHangMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang_BanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SdtSearchText;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private swing.PanelGradiente panelGradiente1;
    private javax.swing.JTable tbl_KhachHang_BanHang;
    // End of variables declaration//GEN-END:variables
}
